services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

  catalogdb:
   container_name: catalogdb
   image: postgres

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.0



volumes:
 postgres_catalog:
 elastic_search_data:   