services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionString__Database=Server=catalogdb;Port=65432;Database=CatalogDb;User Id=postgres;Password=postgres;
      - ConnectionStrings__ElasticSearch=http://elasticsearch:9200
    ports:
      - "6000:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
        - catalogdb
        - elasticsearch

  catalogdb:
   container_name: catalogdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
   restart: always
   ports:
    - "65432:5432" 
   volumes:
   - postgres_catalog:/var/lib/postgresql/data/

  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data

  kibana:
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch