services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Discount/Discount.Grpc/Dockerfile

  catalogdb:
   image: postgres

  basketdb:
   image: postgres

  distributedcache:
      image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0

volumes:
 postgres_catalog:
 postgres_basket:
 elastic_search_data:   
